services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: reservations
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d reservations"] 
      interval: 10s
      timeout: 5s
      retries: 20
      
  app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    command:
        - sh
        - -c
        - "./wait-for-db.sh db yarn start:dev"
    volumes:
        - .:/usr/src/app
        - /usr/src/app/node_modules
        - /usr/src/app/dist
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy 
    env_file:
      - .env 
      
volumes:
  pgdata: