
services:
  db_test:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: reservations_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d reservations_test"]
      interval: 10s
      timeout: 5s
      retries: 20
