services:
  db_test:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: reservations_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d reservations_test"]
      interval: 10s
      timeout: 5s
      retries: 20

  test_runner:
    image: node:20
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    depends_on:
      db_test:
        condition: service_healthy
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: reservations_test
    command: ["sh", "./wait-for-db.sh", "db_test", "yarn", "test:e2e"]